import { sortAndStar } from '../Easy/E_sortAndStar';

describe('sortAndStar()', () => {
  it('Sample tests', () => {
    expect(
      sortAndStar([
        'bitcoin',
        'take',
        'over',
        'the',
        'world',
        'maybe',
        'who',
        'knows',
        'perhaps',
      ])
    ).toBe('b***i***t***c***o***i***n');
    expect(
      sortAndStar([
        'turns',
        'out',
        'random',
        'test',
        'cases',
        'are',
        'easier',
        'than',
        'writing',
        'out',
        'basic',
        'ones',
      ])
    ).toBe('a***r***e');
    expect(
      sortAndStar([
        'lets',
        'talk',
        'about',
        'javascript',
        'the',
        'best',
        'language',
      ])
    ).toBe('a***b***o***u***t');
    expect(
      sortAndStar([
        'i',
        'want',
        'to',
        'travel',
        'the',
        'world',
        'writing',
        'code',
        'one',
        'day',
      ])
    ).toBe('c***o***d***e');
    expect(
      sortAndStar([
        'Lets',
        'all',
        'go',
        'on',
        'holiday',
        'somewhere',
        'very',
        'cold',
      ])
    ).toBe('L***e***t***s');
  });
});
